# (c) https://github.com/MontiCore/monticore

image: openjdk:11-jdk

stages:
  - build
  - deploy
  - check

before_script:
  - chmod +x gradlew
  - export GRADLE_USER_HOME=`pwd`/.gradle
  # TODO: use image with jdk 11 and node 16
  - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
  - apt-get install -y nodejs

cache:
  paths:
    - ".gradle/wrapper"
    - ".gradle/caches"

build:
  stage: build
  script:
    - "./gradlew build -PgithubUser=$githubUser -PgithubToken=$githubToken $GRADLE_OPT $ARGS1"
  artifacts:
    paths:
      - "language/target/"
      - "visualization/target/"
      - "language-server/target/generated-sources/SysML4Verification/plugins/sysml4verification-vscode-plugin"
    expire_in: 1 week

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - "./gradlew publish -PnexusPassword=$pass -PnexusUser=$user -PgithubUser=$githubUser -PgithubToken=$githubToken $GRADLE_OPT $ARGS2"
    - export VERSION=$(./gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file language-server/target/generated-sources/SysML4Verification/plugins/sysml4verification-vscode-plugin/SysML4Verification-${VERSION}.vsix "https://git.rwth-aachen.de/api/v4/projects/37093/packages/generic/sysml4verification-vscode-plugin/${VERSION}/sysml4verification-vscode-plugin-${VERSION}.vsix"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file language-server/target/generated-sources/SysML4Verification/plugins/sysml4verification-vscode-plugin/SysML4Verification-${VERSION}.vsix "https://git.rwth-aachen.de/api/v4/projects/37093/packages/generic/sysml4verification-vscode-plugin/latest/sysml4verification-vscode-plugin-latest.vsix"'
  only:
    - master

# TODO Kaputt: Vermutlich ist das "secibuildtoken" nicht konfiguriert
.checkMDLinks:
  stage: check
  dependencies:
    - build
  script:
    - "curl --location --header \"PRIVATE-TOKEN: $secibuildtoken\" \"https://git.rwth-aachen.de/api/v4/projects/monticore%2Fmdlinkchecker/jobs/artifacts/master/raw/target/libs/MDLinkCheckerCLI.jar?job=build\" --output MDLinkCheckerCLI.jar"
    - "url=https://git.rwth-aachen.de/monticore/languages/xml/-/tree/develop"
    - "linkCheckRes=$(java -jar MDLinkCheckerCLI.jar -url $url -t $secibuildtoken -p)"
    - "echo \"$linkCheckRes\""
    - "if [[ $linkCheckRes == *\"ERROR\"* ]]; then exit 1; fi"
  only:
    - master
