# (c) https://github.com/MontiCore/monticore
stages:
  - gradle
  - docker

before_script:
  - chmod +x gradlew
  - export GRADLE_USER_HOME=`pwd`/.gradle
  # TODO: use image with jdk 11 and node 16
  - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
  - apt-get install -y nodejs

cache:
  paths:
    - ".gradle/wrapper"
    - ".gradle/caches"

# Gradle build with artifacts for convenient download and debugging purposed
build:
  stage: gradle
  image: openjdk:11-jdk
  script:
    - "./gradlew build -PgithubUser=$githubUser -PgithubToken=$githubToken $GRADLE_OPT $ARGS1"
  artifacts:
    paths:
      - "language/target/"
      - "language4verification/target/libs"
      - "visualization/target/"
      - "language-server/target/generated-sources/SysML4Verification/plugins/sysml4verification-vscode-plugin"
    expire_in: 1 week
  except:
    - master
    - /^release/.*$/

# Gradle publish and additional raw binary upload of the built language server plugin for VSCode. Only on master and
# release branches.
# TODO Das "latest" ist sowieso etwas unglücklich und sollte irgendwann verschwinden.
# TODO publish scheint nicht das gleiche wie build zu tun
deploy:
  stage: gradle
  image: openjdk:11-jdk
  script:
    - "./gradlew build publish -PnexusPassword=$pass -PnexusUser=$user -PgithubUser=$githubUser -PgithubToken=$githubToken $GRADLE_OPT $ARGS2"
    - export VERSION=$(./gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file language-server/target/generated-sources/SysML4Verification/plugins/sysml4verification-vscode-plugin/SysML4Verification-${VERSION}.vsix "https://git.rwth-aachen.de/api/v4/projects/37093/packages/generic/sysml4verification-vscode-plugin/${VERSION}/sysml4verification-vscode-plugin-${VERSION}.vsix"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file language-server/target/generated-sources/SysML4Verification/plugins/sysml4verification-vscode-plugin/SysML4Verification-${VERSION}.vsix "https://git.rwth-aachen.de/api/v4/projects/37093/packages/generic/sysml4verification-vscode-plugin/latest/sysml4verification-vscode-plugin-latest.vsix"'
  artifacts:
    paths:
      - "language/target/"
      - "language4verification/target/libs"
      - "visualization/target/"
      - "language-server/target/generated-sources/SysML4Verification/plugins/sysml4verification-vscode-plugin"
    expire_in: 1 week
  only:
    - master
    - /^release/.*$/

# Uses the artifacts from the build jobs
deploy docker:
  stage: docker
  image: docker:19.03.8
  services:
    - docker:18-dind
  before_script:
    - chmod +x gradlew
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - export VERSION=$(./gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')
    - docker build -t $CI_REGISTRY_IMAGE/language4verification-cli:$VERSION ./language4verification
    - docker push $CI_REGISTRY_IMAGE/language4verification-cli:$VERSION
  tags:
    - shell
  only:
    - master
    - /^release/.*$/
