package de.monticore.lang.sysmlactivitydiagrams._ast;

public class ASTSendActionUsage extends ASTSendActionUsageTOP {

  // Name is optional for send action usages, hence why this method was not generated by MontiCore
  @Override
  public String getName() {
    // TODO
    return "";
  }

}
