package de.monticore.lang.sysmlv2;

import de.monticore.lang.sysmlv2._ast.ASTConstraintUsage;
import de.monticore.lang.sysmlv2._ast.ASTSysMLModel;
import de.se_rwth.commons.logging.Log;

import java.nio.file.Paths;

public class SysMLv2Tool extends SysMLv2ToolTOP {
  private long startTimeGlobal;
  @Override
  public void init() {
    var startTime = System.nanoTime();
    startTimeGlobal = startTime;
    super.init();
    var elapsed = System.nanoTime() - startTime;
    System.out.println("Mill init: " + elapsed/1000/1000);
  }

  @Override
  public ASTConstraintUsage parse(String model) {
    var startTime = System.nanoTime();
    var ast = super.parse(model);
    var elapsed = System.nanoTime() - startTime;
    System.out.println(Paths.get(model).getFileName() + ": " + elapsed/1000/1000);
    System.out.println("Total" + ": " + (System.nanoTime()/1000/1000 - startTimeGlobal/1000/1000));
    return ast;
  }


  public void run (String [] args) {
    /* generated by template _cli.Run*/

    String optionVal = "";
    init();
    org.apache.commons.cli.Options options = initOptions();
    try{
      //create CLI Parser and parse input options from commandline
      org.apache.commons.cli.CommandLineParser cliparser = new org.apache.commons.cli.DefaultParser();
      org.apache.commons.cli.CommandLine cmd = cliparser.parse(options,args);

      //help: when --help
      if(cmd.hasOption("h")){
        printHelp(options);
        //do not continue, when help is printed.
        return;
      }
      //version: when --version
      else if(cmd.hasOption("v")){
        printVersion();
        //do not continue when help is printed
        return;
      }

      optionVal = cmd.getOptionValue("s").replace("%", " ");

    }catch (org.apache.commons.cli.ParseException e) {
      // e.getMessage displays the incorrect input-parameters
      Log.error("0xA5C06x33289 Could not process SysMLv2Tool parameters: " + e.getMessage());
    }

    parse(optionVal);
  }
}
